from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 240, 68, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 140, 68, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 80, 68, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 80, 68, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(770, 140, 68, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(890, 240, 68, 19))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(770, 330, 68, 19))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(590, 430, 68, 19))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(370, 430, 68, 19))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 330, 68, 19))
        self.label_10.setObjectName("label_10")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(320, 220, 401, 171))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.game_name = QtWidgets.QLabel(self.centralwidget)
        self.game_name.setGeometry(QtCore.QRect(480, 10, 341, 31))
        self.game_name.setLineWidth(1)
        self.game_name.setObjectName("game_name")
        self.num1 = QtWidgets.QLabel(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(60, 200, 68, 19))
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QLabel(self.centralwidget)
        self.num2.setGeometry(QtCore.QRect(200, 110, 68, 19))
        self.num2.setObjectName("num2")
        self.num3 = QtWidgets.QLabel(self.centralwidget)
        self.num3.setGeometry(QtCore.QRect(370, 50, 68, 19))
        self.num3.setObjectName("num3")
        self.num4 = QtWidgets.QLabel(self.centralwidget)
        self.num4.setGeometry(QtCore.QRect(580, 50, 81, 19))
        self.num4.setObjectName("num4")
        self.num5 = QtWidgets.QLabel(self.centralwidget)
        self.num5.setGeometry(QtCore.QRect(770, 110, 68, 19))
        self.num5.setObjectName("num5")
        self.num6 = QtWidgets.QLabel(self.centralwidget)
        self.num6.setGeometry(QtCore.QRect(890, 210, 68, 19))
        self.num6.setObjectName("num6")
        self.num7 = QtWidgets.QLabel(self.centralwidget)
        self.num7.setGeometry(QtCore.QRect(770, 300, 68, 19))
        self.num7.setObjectName("num7")
        self.num8 = QtWidgets.QLabel(self.centralwidget)
        self.num8.setGeometry(QtCore.QRect(590, 400, 68, 19))
        self.num8.setObjectName("num8")
        self.num9 = QtWidgets.QLabel(self.centralwidget)
        self.num9.setGeometry(QtCore.QRect(370, 400, 68, 19))
        self.num9.setObjectName("num9")
        self.num10 = QtWidgets.QLabel(self.centralwidget)
        self.num10.setGeometry(QtCore.QRect(200, 300, 68, 19))
        self.num10.setObjectName("num10")
        self.mode_text = QtWidgets.QLabel(self.centralwidget)
        self.mode_text.setGeometry(QtCore.QRect(880, 400, 201, 31))
        self.mode_text.setText("")
        self.mode_text.setObjectName("mode_text")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(30, 40, 141, 51))
        self.play.setObjectName("play")
        self.game_ower = QtWidgets.QLabel(self.centralwidget)
        self.game_ower.setGeometry(QtCore.QRect(360, 550, 321, 41))
        self.game_ower.setText("")
        self.game_ower.setObjectName("game_ower")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ДЕТЕКТИВ"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.game_name.setText(_translate("MainWindow", "ДЕТЕКТИВ"))
        self.num1.setText(_translate("MainWindow", "Первый"))
        self.num2.setText(_translate("MainWindow", "Второй"))
        self.num3.setText(_translate("MainWindow", "Третий"))
        self.num4.setText(_translate("MainWindow", "Четвёртый"))
        self.num5.setText(_translate("MainWindow", "Пятый"))
        self.num6.setText(_translate("MainWindow", "Шестой"))
        self.num7.setText(_translate("MainWindow", "Седьмой"))
        self.num8.setText(_translate("MainWindow", "Восьмой"))
        self.num9.setText(_translate("MainWindow", "Девятый"))
        self.num10.setText(_translate("MainWindow", "Десятый"))
        self.play.setText(_translate("MainWindow", "Начать игру"))
